language: node_js
node_js:
  - 12.16.1
sudo: required
branches:
  only:
    - master
services:
  - docker
cache: npm

script:
  - bash test-frontend.sh

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
