language: javascript
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - docker-compose build --pull
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push
