version: "3"

volumes:
  postgres:

services:
  backend:
    build:
      context: backend/
    image: mindaugas16/mine-house-backend
    depends_on:
      - postgres
    environment:
      - TZ=Europe/Vilnius
      - PORT=3000
      - DB_NAME=realestates
      - DB_USERNAME=mindaugas
      - DB_PASSWORD=labasrytas
      - DB_HOST=postgres
      - CRAWLER_HOST=crawler
    ports:
      - 3000:3000
    links:
      - crawler

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=realestates
      - POSTGRES_USER=mindaugas
      - POSTGRES_PASSWORD=labasrytas
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    build:
      context: frontend/
    image: mindaugas16/mine-house-frontend
    ports:
      - 80:80

  crawler:
    build:
      context: crawler/
    image: mindaugas16/mine-house-crawler
    expose:
      - 5000
