version: "3"

volumes:
  postgres:

services:
  backend:
    build:
      context: backend/
    image: mindaugas16/mine-house-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000
    links:
      - crawler

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    build:
      context: frontend/
    image: mindaugas16/mine-house-frontend
    ports:
      - 80:80

  crawler:
    build:
      context: crawler/
    image: mindaugas16/mine-house-crawler
    restart: always
    expose:
      - 5000
