version: "3"

volumes:
  postgres:

services:
  backend:
    build: backend/
    restart: always
    depends_on:
      - postgres
    environment:
      - TZ=Europe/Vilnius
      - DB_NAME=realestates
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - CRAWLER_HOST=crawler
    ports:
      - 3000:3000
    links:
      - crawler

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=realestates
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localhost
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    build: frontend/
    ports:
      - 80:80

  crawler:
    build: crawler/
    restart: always
    expose:
      - 5000
