version: "3"

volumes:
  postgres:

services:
  backend:
    build: backend/
    depends_on:
      - postgres
    environment:
      - TZ=Europe/Vilnius
      - DB_NAME=realestates
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
    ports:
      - 3000:3000
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=realestates
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    build: frontend/
    depends_on:
      - backend
      - postgres
    ports:
      - 80:80
