version: "3.7"

volumes:
  postgres:

services:
  postgres:
    image: postgres
    environment:
        POSTGRES_DB: ${POSTGRES_DB_NAME}
        POSTGRES_USER: ${POSTGRES_DB_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}

  backend:
    build:
      context: backend/
    image: mindaugas16/mine-house-backend
    depends_on:
      - postgres
    environment:
        TZ: ${TZ}
        APP_SERVER_PORT: ${APP_SERVER_PORT}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
        POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
        POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
        POSTGRES_DB_HOST: ${POSTGRES_DB_HOST}
        CRAWLER_HOST: ${CRAWLER_HOST}
        CRAWLER_PORT: ${CRAWLER_PORT}
    ports:
      - 3000:3000
    links:
      - crawler

  frontend:
    build:
      context: frontend/
    image: mindaugas16/mine-house-frontend
    links:
      - backend
    ports:
      - ${VUE_APP_PORT}:${VUE_APP_PORT}
    expose:
      - ${VUE_APP_PORT}


  crawler:
    build:
      context: crawler/
    image: mindaugas16/mine-house-crawler
    expose:
      - ${CRAWLER_PORT}
