version: '3'

volumes:
  mongodb_volume:

services:
  backend:
    build: backend/
    restart: always
    environment:
      - TZ=Europe/Vilnius
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
    ports:
      - 3000:3000

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    environment:
      - TZ=Europe/Vilnius
    restart: always
    ports:
      - 27017:27017
