export const UPDATE_REAL_ESTATES = 'UPDATE_REAL_ESTATES';
export const UPDATE_REAL_ESTATE = 'UPDATE_REAL_ESTATE';
export const UPDATE_REAL_ESTATES_META = 'UPDATE_REAL_ESTATES_META';
export const LOADING = 'LOADING';
