export const UPDATE_REAL_ESTATES = 'UPDATE_REAL_ESTATES';
export const UPDATE_REAL_ESTATE = 'UPDATE_REAL_ESTATE';
export const UPDATE_REAL_ESTATES_META = 'UPDATE_REAL_ESTATES_META';
export const LOADING = 'LOADING';
export const SET_REAL_ESTATE = 'SET_REAL_ESTATE';

export const SET_CRAWLERS = 'SET_CRAWLERS';
export const CRAWLERS_LOADING = 'CRAWLERS_LOADING';
export const DELETE_CRAWLER = 'DELETE_CRAWLER';
export const ADD_CRAWLER = 'ADD_CRAWLER';
export const PATCH_CRAWLER = 'PATCH_CRAWLER';
export const SET_SELECTED_CRAWLER = 'SET_SELECTED_CRAWLER';
